### ISSUE TITLE
robustlmm super slow on large dataset

### ISSUE THREAD

**Issue by sneupane2** [kollerma/robustlmm#19]
Sorry, I am new to this but I am using robustlmm (rlmer) for my dataset with 7million observations. It was taking forever, so, I quit after 2 days. Is there any other way to do it efficiently?
In the lme4 (glmer function), for the same dataset, when used 'nAGQ=0' in the model. it was just a matter of a couple of minutes. Is there any package or method we can use to do robust standard errors for binomial logit (hierarchical models)?

**Comment by kollerma** [comment]
robustlmm (rlmer) is only suitable for continuous responses. It is an alternative to lmer not glmer. I am not aware of any robust alternative to glmer. If you're only looking to get robust standard errors, then you might want to have a look at the [merDeriv package](https://www.jstatsoft.org/article/view/v087c01).

It is expected that rlmer is a lot slower than lmer. rlmer also requires a lot more memory in the process than lmer. That is because rlmer has to do a lot more work trying to fit the model in a robust way, e.g., while trying to filter out bad observations.

**Comment by sneupane2** [comment]
I got this message when using sandwich:
Error in UseMethod("estfun") : 
  no applicable method for 'estfun' applied to an object of class "c('glmerMod', 'merMod')"
