### ISSUE TITLE
Error: invalid assignment for reference class field ‘b.s’, should be from class “numeric” or a subclass (was class “dgeMatrix”)

### ISSUE THREAD

**Issue by Satoshi-Young** [kollerma/robustlmm#28]
Hi, 
Thank you for creating this package. But I encountered a problem when I use rlmer(). That is an error: 
`Error: invalid assignment for reference class field ‘b.s’, should be from class “numeric” or a subclass (was class “dgeMatrix”)`
But these data will be modeled successfully when I use lmer(). Even when I run the example about 'Penicillin' in your article, the error also occurs. Did I do something wrong and could you give me some suggestions, please. Thank you!

**Comment by kollerma** [comment]
Hello
Checks are still passing, so this may be due to a bad interaction of packages installed / updated different times. To debug this, I need a bit more information. 

Could you please: 
1. Reproduce the problem on your machine. And then post the output of `sessionInfo()` run right after.
2. Update all R packages to their newest versions. And check whether the problem is still happening. 
Thanks.

**Comment by Satoshi-Young** [comment]
Thank you very much! I updated lme4 and Matrix according to your suggestion, and this problem has been solved.
